### ISSUE TITLE
User roles (RBAC)

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#2245]
**Update:** Tracking progress in the `rbac` feature branch, since this is a big undertaking, I want @IvanaH8 and @0mar to be able to land incremental progress PRs without one enormous PR

Progress:

- [x] define and document scopes in the rest api (#3169)
- [x] implement scope permission checks on handlers (#3212)
- [x] implement scopes, roles in the database (#3215)
- [x] utilities for resolving roles -> scopes for matching
- [x] use scopes to filter model content (e.g. applying `read:user:name` on `GET /users`)
- [x] narrative docs describing how to work with scopes and roles
- [x] eliminate OAuthToken as separate entity, instead relying on APITokens with different scopes
- [ ] UI for creating tokens with specified scopes or roles

----

Original description:

For 1.0, I plan to have an implementation of oauth scopes for tokens (#1057). But @ellisonbg has also proposed the addition of "roles" for RBAC-style authentication of users themselves. I think we won't get to this for the next release, but we should start to sketch out what kind of roles we might have and what they would be used for. There will presumably be quite a bit of interaction between scopes and roles.

The difference between roles and scopes:

- a scope has specific permissions (e.g. start/stop servers)
- a role is a named reference to a collection of scopes (e.g. server-admin)
- roles are not themselves generally used for authorization, only for resolving scopes

This means:

- When a user or token has scopes directly, the user or token must be modified to change their access
- When a user or token has a 'role', only the role needs to be updated with changed scopes, and all users or tokens with that role immediately receive that change in permission

What kind of roles should we have, and do we need full user-defined roles so that admins can create and manage their own collections of roles, etc.?

**Comment by minrk** [comment]
Further, how much should this be (or be able to be) deferred to an identity provider vs a purely internal construct.

**Comment by mangecoeur** [comment]
+1 to this. I've was thinking how to manage this for our lab. The use case is: we have a shared compute server, auth is done using local (PAM auth) users. We have permanent staff who have elevated privileges on the server and students who come and go - e.g. for a class we might need to create a bunch of user accounts with limited permissions and delete them later.

I would suggest a built in identity provider that by default maps to linux system users, but that can be replaced/enhanced by pluggable backends similar to how the current auth system works. That way the simplest install (directly installed on a linux server) Just Works. Many auth providers can't also provide identity information to associate roles with users so having an internal construct is probably necessary. For PAM auth it could be possible to pick up the user 's system groups and use them to define roles - this might be a good idea to allow permissions to be matched between jupyterlab and what they can do on the console.

I currently fake this using user permissions and some user creation/deletion scripts (so e.g. adding users for a class is a matter of running a bash script with a list of usernames) - not very elegant!

**Comment by ellisonbg** [comment]
Thanks @minrk for getting this started. Also ping @SylvainCorlay who is working on dashboard related things where this is relevant.

I think it will be helpful to have both scopes and roles. Conceptually I see scopes are to roles as users are to groups.

In terms of what specific scopes there should be I can imagine different ones for different parts of the architecture. 

One part that we have been thinking about is having different scopes for the single user notebook server. Some of the ones that have come up:

* r/w scope for the content manager to allow for users that can only view files.
* a scope that allows a user to run code using kernels. We might want separate ones for the REST API of kernels from the websocket one. @SylvianCorlay also has a mode for the new jupyter server that allows the code for a kernel to be loaded at kernel start time and then run only by an opaque uuid. This is being used for notebook based dashboards where a user should be able to run existing code, but not arbitrary new code.

Then there are definitely scopes associate with the hub itself:

* Manage users (part of a server admin role)
* Talk to spawners (for things such as cull idle).
* Ones that allow writing to logging endpoints.

Definitely makes sense to start simple and see how it goes.

**Comment by consideRatio** [comment]
# Regarding terminology
I wanted to translate this into a Kubernetes representation so think about it more clearly in terms I'm used to. JupyterHub has not strict coupling to kubernetes and this is just to help me connect know-how in that domain to JupyterHub.

## Kubernetes RBAC
- **Role** - a _set of permissions_, called _Rules_. It can also be an aggregation of permissions from other Roles.
- **RoleBinding** - A coupling of a Role to a ServiceAccount
- **ServiceAccount** - An identity

## JupyterHub RBAC terminology
- **Role** - A set of permissions, called _Scopes_.
- **User** - An identity

## Summary of thoughts
- The k8s _Role_ is what @minrk named _Scope_.
- The k8s _RoleBinding_ has no explicitly mentioned equivalent, but it could end up being belonging to a group of users or similar perhaps, I'm not sure.
- The k8s ServiceAccount matches to the JupyterHub user identity.

**Comment by minrk** [comment]
I was thinking we'd actually be even closer to kubernetes, so I'd revise the JupyterHub terminology a bit. I didn't mention RoleBinding specifically, but the concept still exists in terms of assigning Accounts to Roles. If we don't create RoleBindings as a separate thing to manage, we can let the Role assignment reside directly on User or Group objects (I'm not sure if the trade-off of centralizing bindings vs simpler User properties would be better or not).

## JupyterHub RBAC terminology

- **Scope**: name identifying permission to take a particular action (kubernetes analog: apiGroup + verb)
- **Role**: collection of scopes (just like kubernetes Roles are collections of apiGroups+verbs)
- **RoleBinding**: assign Accounts to Roles (identical to kubernetes). *may* be a separate API resource, *may* be user/group property. Implementation detail.
- **Accounts**: we have three ways to identify people and things: User (accounts for humans), Service (accounts for non-humans), and Group (collections of Users)

This maps very well to my experience with RBAC-enabled AKS, where one creates RoleBindings for active directory users based on account id, group membership, etc.
